python3 - << 'ENDSCRIPT'
import os
BASE = os.getcwd()
files = {}

files["src/app/globals.css"] = """\
/* LAKSOR — Design System Global */
:root {
  --sand: #F6F1E8;
    --sand-dark: #EADCC8;
      --bronze: #B88A44;
        --bronze-dark: #A17635;
          --sage: #7D8F69;
            --sage-dark: #6A7A58;
              --charcoal: #111111;
                --white: #FFFFFF;
                  --grey: #888888;
                    --grey-light: #E5E5E5;
                      --gradient-bronze: linear-gradient(135deg, #B88A44, #A17635);
                        --gradient-hero: linear-gradient(180deg, rgba(0,0,0,0.35) 0%, rgba(0,0,0,0.65) 100%);
                          --font-title: var(--font-playfair), Georgia, serif;
                            --font-body: var(--font-inter), sans-serif;
                              --radius-card: 24px;
                                --radius-btn: 999px;
                                  --radius-modal: 32px;
                                    --radius-input: 999px;
                                      --radius-badge: 999px;
                                        --shadow-card: 0 10px 40px rgba(0,0,0,0.06);
                                          --shadow-bronze: 0 4px 16px rgba(184,138,68,0.30);
                                            --shadow-hover: 0 20px 60px rgba(0,0,0,0.12);
                                              --section-padding: 96px;
                                                --navbar-height: 80px;
                                                  --transition: all 0.2s ease;
                                                  }
                                                  *, *::before, *::after { box-sizing: border-box; padding: 0; margin: 0; }
                                                  html { scroll-behavior: smooth; }
                                                  html, body { max-width: 100vw; overflow-x: hidden; }
                                                  body {
                                                    color: var(--charcoal);
                                                      background: var(--sand);
                                                        font-family: var(--font-body);
                                                          font-size: 16px;
                                                            line-height: 1.6;
                                                              -webkit-font-smoothing: antialiased;
                                                              }
                                                              h1,h2,h3,h4,h5,h6 { font-family: var(--font-title); font-weight: 700; line-height: 1.2; color: var(--charcoal); }
                                                              h1 { font-size: clamp(2.4rem,5vw,4rem); }
                                                              h2 { font-size: clamp(1.8rem,3vw,2.8rem); }
                                                              h3 { font-size: clamp(1.3rem,2vw,1.8rem); }
                                                              a { color: inherit; text-decoration: none; transition: var(--transition); }
                                                              ::-webkit-scrollbar { width: 6px; }
                                                              ::-webkit-scrollbar-track { background: var(--sand); }
                                                              ::-webkit-scrollbar-thumb { background: var(--bronze); border-radius: 999px; }
                                                              .container { max-width: 1200px; margin: 0 auto; padding: 0 24px; }
                                                              @keyframes fadeUp { from { opacity:0; transform:translateY(20px); } to { opacity:1; transform:translateY(0); } }
                                                              @keyframes spin { to { transform: rotate(360deg); } }
                                                              :focus-visible { outline: 2px solid var(--bronze); outline-offset: 2px; }
                                                              @media (max-width:768px) { :root { --section-padding:60px; --navbar-height:68px; } }
                                                              """

                                                              files["src/app/layout.tsx"] = """\
                                                              import type { Metadata } from "next";
                                                              import { Playfair_Display, Inter } from "next/font/google";
                                                              import "./globals.css";

                                                              const playfair = Playfair_Display({
                                                                subsets: ["latin"],
                                                                  variable: "--font-playfair",
                                                                    display: "swap",
                                                                      weight: ["400","500","600","700","800"],
                                                                      });
                                                                      const inter = Inter({ subsets: ["latin"], variable: "--font-inter", display: "swap" });

                                                                      export const metadata: Metadata = {
                                                                        title: "LAKSOR — Guides Locaux Certifiés au Maroc",
                                                                          description: "Réservez une visite guidée authentique à Marrakech, Fès, Essaouira, Chefchaouen ou Agadir avec des guides locaux certifiés.",
                                                                            keywords: ["guide touristique maroc","visite guidée marrakech","guide local fès"],
                                                                              openGraph: {
                                                                                  title: "LAKSOR — Guides Locaux Certifiés au Maroc",
                                                                                      description: "Réservez une visite guidée authentique avec des guides locaux certifiés.",
                                                                                          siteName: "LAKSOR", locale: "fr_FR", type: "website",
                                                                                            },
                                                                                            };

                                                                                            export default function RootLayout({ children }: { children: React.ReactNode }) {
                                                                                              return (
                                                                                                  <html lang="fr" className={`${playfair.variable} ${inter.variable}`}>
                                                                                                        <body>{children}</body>
                                                                                                            </html>
                                                                                                              );
                                                                                                              }
                                                                                                              """

                                                                                                              files["src/styles/tokens.ts"] = """\
                                                                                                              export const COLORS = {
                                                                                                                sand:"#F6F1E8", sandDark:"#EADCC8",
                                                                                                                  bronze:"#B88A44", bronzeDark:"#A17635",
                                                                                                                    sage:"#7D8F69", sageDark:"#6A7A58",
                                                                                                                      charcoal:"#111111", white:"#FFFFFF",
                                                                                                                        grey:"#888888", greyLight:"#E5E5E5",
                                                                                                                        } as const;

                                                                                                                        export const GRADIENTS = {
                                                                                                                          bronze:"linear-gradient(135deg,#B88A44,#A17635)",
                                                                                                                            hero:"linear-gradient(180deg,rgba(0,0,0,0.35) 0%,rgba(0,0,0,0.65) 100%)",
                                                                                                                              sand:"linear-gradient(180deg,#F6F1E8 0%,#EADCC8 100%)",
                                                                                                                              } as const;

                                                                                                                              export const FONTS = {
                                                                                                                                title:"var(--font-playfair),Georgia,serif",
                                                                                                                                  body:"var(--font-inter),sans-serif",
                                                                                                                                  } as const;

                                                                                                                                  export const RADIUS = {
                                                                                                                                    card:"24px", btn:"999px", modal:"32px",
                                                                                                                                      input:"999px", badge:"999px", sm:"12px",
                                                                                                                                      } as const;

                                                                                                                                      export const SHADOWS = {
                                                                                                                                        card:"0 10px 40px rgba(0,0,0,0.06)",
                                                                                                                                          bronze:"0 4px 16px rgba(184,138,68,0.30)",
                                                                                                                                            hover:"0 20px 60px rgba(0,0,0,0.12)",
                                                                                                                                            } as const;

                                                                                                                                            export const TRANSITIONS = {
                                                                                                                                              fast:"all 0.15s ease", base:"all 0.2s ease", slow:"all 0.4s ease",
                                                                                                                                              } as const;

                                                                                                                                              export type ColorKey = keyof typeof COLORS;
                                                                                                                                              """

                                                                                                                                              files["src/components/ui/Logo.tsx"] = '''\
                                                                                                                                              "use client";
                                                                                                                                              import React from "react";
                                                                                                                                              type LogoSize = "xs"|"sm"|"md"|"lg"|"xl";
                                                                                                                                              type LogoVariant = "dark"|"light"|"bronze";
                                                                                                                                              interface LogoProps { size?:LogoSize; variant?:LogoVariant; showTagline?:boolean; style?:React.CSSProperties; }
                                                                                                                                              const fontSizes:Record<LogoSize,number> = {xs:14,sm:18,md:22,lg:28,xl:36};
                                                                                                                                              const colorMap:Record<LogoVariant,string> = {dark:"#111111",light:"#FFFFFF",bronze:"#B88A44"};
                                                                                                                                              export function Logo({size="md",variant="bronze",showTagline=false,style}:LogoProps) {
                                                                                                                                                const fontSize = fontSizes[size];
                                                                                                                                                  const color = colorMap[variant];
                                                                                                                                                    return (
                                                                                                                                                        <div style={{display:"inline-flex",flexDirection:"column",alignItems:"flex-start",gap:2,...style}}>
                                                                                                                                                              <span style={{fontFamily:"var(--font-playfair),Georgia,serif",fontSize,fontWeight:700,color,letterSpacing:"0.12em",lineHeight:1,textTransform:"uppercase"}}>LAKSOR</span>
                                                                                                                                                                    {showTagline && <span style={{fontFamily:"var(--font-inter),sans-serif",fontSize:fontSize*0.38,fontWeight:400,color:variant==="light"?"rgba(255,255,255,0.65)":"#888888",letterSpacing:"0.15em",textTransform:"uppercase"}}>Guides Locaux · Maroc</span>}
                                                                                                                                                                        </div>
                                                                                                                                                                          );
                                                                                                                                                                          }
                                                                                                                                                                          '''

                                                                                                                                                                          files["src/components/ui/Button.tsx"] = '''\
                                                                                                                                                                          "use client";
                                                                                                                                                                          import React from "react";
                                                                                                                                                                          type ButtonVariant = "primary"|"secondary"|"sage"|"ghost"|"outline";
                                                                                                                                                                          type ButtonSize = "sm"|"md"|"lg";
                                                                                                                                                                          interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
                                                                                                                                                                            variant?:ButtonVariant; size?:ButtonSize; fullWidth?:boolean; loading?:boolean;
                                                                                                                                                                              icon?:React.ReactNode; iconPosition?:"left"|"right";
                                                                                                                                                                              }
                                                                                                                                                                              const V:Record<ButtonVariant,React.CSSProperties> = {
                                                                                                                                                                                primary:   {background:"linear-gradient(135deg,#B88A44,#A17635)",color:"#fff",border:"none",boxShadow:"0 4px 16px rgba(184,138,68,0.30)"},
                                                                                                                                                                                  secondary: {background:"#fff",color:"#111",border:"1.5px solid #EADCC8"},
                                                                                                                                                                                    sage:      {background:"rgba(125,143,105,0.10)",color:"#7D8F69",border:"1.5px solid #7D8F69"},
                                                                                                                                                                                      ghost:     {background:"rgba(255,255,255,0.15)",color:"#fff",border:"1.5px solid rgba(255,255,255,0.30)",backdropFilter:"blur(10px)"},
                                                                                                                                                                                        outline:   {background:"transparent",color:"#B88A44",border:"1.5px solid #B88A44"},
                                                                                                                                                                                        };
                                                                                                                                                                                        const S:Record<ButtonSize,React.CSSProperties> = {
                                                                                                                                                                                          sm:{padding:"8px 18px",fontSize:13},
                                                                                                                                                                                            md:{padding:"12px 28px",fontSize:14},
                                                                                                                                                                                              lg:{padding:"16px 36px",fontSize:16},
                                                                                                                                                                                              };
                                                                                                                                                                                              export function Button({variant="primary",size="md",fullWidth=false,loading=false,icon,iconPosition="left",children,disabled,style,...props}:ButtonProps) {
                                                                                                                                                                                                return (
                                                                                                                                                                                                    <button disabled={disabled||loading}
                                                                                                                                                                                                          onMouseEnter={e=>{if(!disabled&&!loading){e.currentTarget.style.transform="translateY(-1px)";e.currentTarget.style.filter="brightness(1.06)"}}}
                                                                                                                                                                                                                onMouseLeave={e=>{e.currentTarget.style.transform="translateY(0)";e.currentTarget.style.filter="brightness(1)"}}
                                                                                                                                                                                                                      style={{display:"inline-flex",alignItems:"center",justifyContent:"center",gap:8,borderRadius:999,fontFamily:"var(--font-inter),sans-serif",fontWeight:600,cursor:disabled||loading?"not-allowed":"pointer",width:fullWidth?"100%":"auto",transition:"all 0.2s ease",opacity:disabled?0.55:1,whiteSpace:"nowrap",letterSpacing:"0.01em",...V[variant],...S[size],...style}}
                                                                                                                                                                                                                            {...props}>
                                                                                                                                                                                                                                  {loading?<><span style={{width:14,height:14,border:"2px solid rgba(255,255,255,0.3)",borderTopColor:"#fff",borderRadius:"50%",display:"inline-block",animation:"spin 0.7s linear infinite"}}/>{children}</>:<>{icon&&iconPosition==="left"&&icon}{children}{icon&&iconPosition==="right"&&icon}</>}
                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                        '''

                                                                                                                                                                                                                                        files["src/components/ui/Badge.tsx"] = '''\
                                                                                                                                                                                                                                        "use client";
                                                                                                                                                                                                                                        import React from "react";
                                                                                                                                                                                                                                        type BadgeVariant = "bronze"|"sage"|"sand"|"verified"|"pending"|"success"|"error";
                                                                                                                                                                                                                                        interface BadgeProps { variant?:BadgeVariant; children:React.ReactNode; icon?:React.ReactNode; style?:React.CSSProperties; }
                                                                                                                                                                                                                                        const B:Record<BadgeVariant,React.CSSProperties> = {
                                                                                                                                                                                                                                          bronze:  {background:"rgba(184,138,68,0.12)", color:"#B88A44",border:"1px solid rgba(184,138,68,0.25)"},
                                                                                                                                                                                                                                            sage:    {background:"rgba(125,143,105,0.12)",color:"#7D8F69",border:"1px solid rgba(125,143,105,0.25)"},
                                                                                                                                                                                                                                              verified:{background:"rgba(125,143,105,0.12)",color:"#7D8F69",border:"1px solid rgba(125,143,105,0.25)"},
                                                                                                                                                                                                                                                sand:    {background:"#EADCC8",color:"#111111",border:"1px solid #EADCC8"},
                                                                                                                                                                                                                                                  pending: {background:"rgba(184,138,68,0.10)", color:"#9A6F2A",border:"1px solid rgba(184,138,68,0.20)"},
                                                                                                                                                                                                                                                    success: {background:"rgba(125,143,105,0.12)",color:"#7D8F69",border:"1px solid rgba(125,143,105,0.25)"},
                                                                                                                                                                                                                                                      error:   {background:"rgba(220,53,69,0.10)",  color:"#C0392B",border:"1px solid rgba(220,53,69,0.20)"},
                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                      export function Badge({variant="sand",children,icon,style}:BadgeProps) {
                                                                                                                                                                                                                                                        return <span style={{display:"inline-flex",alignItems:"center",gap:4,padding:"4px 10px",borderRadius:999,fontSize:12,fontWeight:600,fontFamily:"var(--font-inter),sans-serif",letterSpacing:"0.02em",whiteSpace:"nowrap",...B[variant],...style}}>{icon&&<span style={{fontSize:11}}>{icon}</span>}{children}</span>;
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                        export function VerifiedBadge() { return <Badge variant="verified" icon="✓">Guide certifié</Badge>; }
                                                                                                                                                                                                                                                        '''

                                                                                                                                                                                                                                                        files["src/components/shared/Navbar.tsx"] = '''\
                                                                                                                                                                                                                                                        "use client";
                                                                                                                                                                                                                                                        import { useState, useEffect } from "react";
                                                                                                                                                                                                                                                        import { createClient } from "@supabase/supabase-js";
                                                                                                                                                                                                                                                        import { Logo } from "@/components/ui/Logo";

                                                                                                                                                                                                                                                        const supabase = createClient(
                                                                                                                                                                                                                                                          process.env.NEXT_PUBLIC_SUPABASE_URL || "",
                                                                                                                                                                                                                                                            process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || ""
                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                            export default function Navbar() {
                                                                                                                                                                                                                                                              const [user, setUser] = useState<any>(null);
                                                                                                                                                                                                                                                                const [guideId, setGuideId] = useState<string|null>(null);
                                                                                                                                                                                                                                                                  const [role, setRole] = useState<string>("");
                                                                                                                                                                                                                                                                    const [menuOpen, setMenuOpen] = useState(false);
                                                                                                                                                                                                                                                                      const [scrolled, setScrolled] = useState(false);

                                                                                                                                                                                                                                                                        useEffect(() => {
                                                                                                                                                                                                                                                                            const onScroll = () => setScrolled(window.scrollY > 10);
                                                                                                                                                                                                                                                                                window.addEventListener("scroll", onScroll);
                                                                                                                                                                                                                                                                                    return () => window.removeEventListener("scroll", onScroll);
                                                                                                                                                                                                                                                                                      }, []);

                                                                                                                                                                                                                                                                                        useEffect(() => {
                                                                                                                                                                                                                                                                                            async function loadUser(u:any) {
                                                                                                                                                                                                                                                                                                  setUser(u);
                                                                                                                                                                                                                                                                                                        const res = await fetch("/api/auth/me?supabaseId="+u.id);
                                                                                                                                                                                                                                                                                                              const data = await res.json();
                                                                                                                                                                                                                                                                                                                    if (data.guideId) setGuideId(data.guideId);
                                                                                                                                                                                                                                                                                                                          setRole(data.role||"");
                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                  supabase.auth.getSession().then(({data:{session}})=>{ if(session?.user) loadUser(session.user); });
                                                                                                                                                                                                                                                                                                                                      supabase.auth.onAuthStateChange((_,session)=>{ if(session?.user) loadUser(session.user); });
                                                                                                                                                                                                                                                                                                                                        }, []);

                                                                                                                                                                                                                                                                                                                                          async function logout() { await supabase.auth.signOut(); window.location.href="/"; }

                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                <nav style={{
                                                                                                                                                                                                                                                                                                                                                      background: scrolled?"rgba(246,241,232,0.96)":"rgba(246,241,232,0.85)",
                                                                                                                                                                                                                                                                                                                                                            backdropFilter:"blur(20px)", WebkitBackdropFilter:"blur(20px)",
                                                                                                                                                                                                                                                                                                                                                                  borderBottom: scrolled?"1px solid rgba(184,138,68,0.15)":"1px solid transparent",
                                                                                                                                                                                                                                                                                                                                                                        padding:"0 clamp(16px,4vw,40px)", height:80,
                                                                                                                                                                                                                                                                                                                                                                              display:"flex", alignItems:"center", justifyContent:"space-between",
                                                                                                                                                                                                                                                                                                                                                                                    position:"sticky", top:0, zIndex:200, transition:"all 0.3s ease",
                                                                                                                                                                                                                                                                                                                                                                                        }}>
                                                                                                                                                                                                                                                                                                                                                                                              <a href="/"><Logo size="lg" variant="bronze"/></a>
                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{display:"flex",alignItems:"center",gap:10}}>
                                                                                                                                                                                                                                                                                                                                                                                                            {!user ? (
                                                                                                                                                                                                                                                                                                                                                                                                                      <>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <a href="/auth/login" style={{fontSize:14,color:"#111",padding:"10px 16px",fontFamily:"var(--font-inter),sans-serif",fontWeight:500,opacity:0.75}}>Se connecter</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <a href="/auth/register" style={{background:"linear-gradient(135deg,#B88A44,#A17635)",color:"#fff",borderRadius:999,padding:"10px 22px",fontSize:13,fontWeight:700,fontFamily:"var(--font-inter),sans-serif",boxShadow:"0 4px 16px rgba(184,138,68,0.30)",textDecoration:"none"}}>Devenir guide</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{position:"relative"}}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button onClick={()=>setMenuOpen(!menuOpen)} style={{display:"flex",alignItems:"center",gap:8,background:"none",border:"1.5px solid #EADCC8",borderRadius:999,padding:"6px 14px",cursor:"pointer"}}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {user.user_metadata?.avatar_url&&<img src={user.user_metadata.avatar_url} alt="" style={{width:28,height:28,borderRadius:"50%",objectFit:"cover"}}/>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span style={{fontSize:13,fontWeight:600,color:"#111",fontFamily:"var(--font-inter),sans-serif"}}>{user.user_metadata?.full_name?.split(" ")[0]||"Mon compte"}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span style={{fontSize:10,color:"#888"}}>▼</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {menuOpen&&(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{position:"absolute",right:0,top:"calc(100% + 8px)",background:"#fff",borderRadius:20,boxShadow:"0 8px 40px rgba(0,0,0,0.12)",border:"1px solid #EADCC8",minWidth:210,overflow:"hidden",zIndex:300}}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <a href="/dashboard/tourist" style={{display:"block",padding:"13px 18px",fontSize:14,color:"#111",borderBottom:"1px solid #F6F1E8",fontWeight:600,fontFamily:"var(--font-inter),sans-serif"}}>🧳 Mes réservations</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {guideId&&<a href={"/dashboard/guide?id="+guideId} style={{display:"block",padding:"13px 18px",fontSize:14,color:"#111",borderBottom:"1px solid #F6F1E8",fontWeight:600,fontFamily:"var(--font-inter),sans-serif"}}>📊 Mon dashboard</a>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {role==="ADMIN"&&<a href="/dashboard/admin" style={{display:"block",padding:"13px 18px",fontSize:14,color:"#111",borderBottom:"1px solid #F6F1E8",fontFamily:"var(--font-inter),sans-serif"}}>⚙️ Admin</a>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button onClick={logout} style={{display:"block",width:"100%",padding:"13px 18px",fontSize:14,color:"#ef4444",border:"none",background:"none",cursor:"pointer",textAlign:"left",fontFamily:"var(--font-inter),sans-serif"}}>🚪 Déconnexion</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              '''

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              created = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              for rel_path, content in files.items():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  full_path = os.path.join(BASE, rel_path)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      os.makedirs(os.path.dirname(full_path), exist_ok=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if os.path.exists(full_path):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  with open(full_path,"r",encoding="utf-8") as f: old=f.read()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          with open(full_path+".bak","w",encoding="utf-8") as f: f.write(old)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              with open(full_path,"w",encoding="utf-8") as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      f.write(content)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          created.append(rel_path)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              print(f"  ✅  {rel_path}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              print(f"\n✅ {len(created)} fichiers créés.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ENDSCRIPT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              