export const dynamic = "force-dynamic";
import { prisma } from "@/lib/prisma";
import { notFound } from "next/navigation";
import Link from "next/link";
import BookingModal from "@/components/BookingModal";
const B="#123EAB",Y="#F4C542",T="#C96B4B",S="#F8F5F0";
export default async function GuidePage({params}:{params:{id:string}}) {
  const guide = await prisma.guideProfile.findUnique({where:{id:params.id},include:{user:true}});
    if (!guide) notFound();
      const stars = Math.round(Number(guide.avgRating)||5);
        return (
            <div style={{background:S,minHeight:"100vh",fontFamily:"Georgia,serif"}}>
                  <div style={{background:"#fff",borderBottom:"1px solid #e8e0d6",padding:"0 24px",height:64,display:"flex",alignItems:"center",justifyContent:"space-between"}}>
                          <Link href="/" style={{textDecoration:"none",display:"flex",alignItems:"center",gap:10}}>
                                    <div style={{width:36,height:36,borderRadius:10,background:B,display:"flex",alignItems:"center",justifyContent:"center",color:"#fff",fontWeight:900,fontSize:16}}>L</div>
                                              <div><div style={{fontWeight:900,fontSize:15,color:B}}>LAKSOR</div><div style={{fontSize:9,color:"#999"}}>TOUR GUIDE MOROCCO</div></div>
                                                      </Link>
                                                              <Link href="/" style={{fontSize:13,color:"#666",textDecoration:"none"}}>Retour</Link>
                                                                    </div>
                                                                          <div style={{position:"relative",height:320,overflow:"hidden"}}>
                                                                                  {guide.avatar?<img src={guide.avatar} alt={guide.displayName} style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<div style={{width:"100%",height:"100%",background:"linear-gradient(135deg,#123EAB,#1a4fd6)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:80}}>🧭</div>}
                                                                                          <div style={{position:"absolute",inset:0,background:"linear-gradient(to top,rgba(0,0,0,0.7),transparent)"}}/>
                                                                                                  <div style={{position:"absolute",bottom:24,left:24,color:"#fff"}}>
                                                                                                            <div style={{fontSize:28,fontWeight:900}}>{guide.displayName}</div>
                                                                                                                      <div style={{fontSize:14,opacity:0.9}}>{guide.city}</div>
                                                                                                                              </div>
                                                                                                                                    </div>
                                                                                                                                          <div style={{maxWidth:720,margin:"0 auto",padding:"32px 20px"}}>
                                                                                                                                                  <div style={{background:"#fff",borderRadius:20,padding:24,marginBottom:20,display:"flex",gap:32}}>
                                                                                                                                                            <div style={{textAlign:"center"}}>
                                                                                                                                                                        <div style={{fontSize:28,fontWeight:900,color:B}}>{Number(guide.avgRating).toFixed(1)}</div>
                                                                                                                                                                                    <div style={{color:Y,fontSize:18}}>{"★".repeat(stars)}</div>
                                                                                                                                                                                                <div style={{fontSize:12,color:"#999"}}>{guide.totalReviews} avis</div>
                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                    <div style={{borderLeft:"1px solid #f0ebe4",paddingLeft:32,display:"flex",gap:24,alignItems:"center"}}>
                                                                                                                                                                                                                                <div style={{textAlign:"center"}}><div style={{fontSize:22,fontWeight:800,color:T}}>{guide.yearsExp||0}</div><div style={{fontSize:11,color:"#999"}}>ans exp.</div></div>
                                                                                                                                                                                                                                            <div style={{textAlign:"center"}}><div style={{fontSize:22,fontWeight:800,color:T}}>{0||0}</div><div style={{fontSize:11,color:"#999"}}>tours</div></div>
                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                      {guide.bio&&<div style={{background:"#fff",borderRadius:20,padding:24,marginBottom:20}}><div style={{fontSize:13,fontWeight:700,color:B,marginBottom:12}}>A PROPOS</div><p style={{fontSize:15,color:"#444",lineHeight:1.7,margin:0}}>{guide.bio}</p></div>}
                                                                                                                                                                                                                                                                              {guide.languages&&(guide.languages as string[]).length>0&&<div style={{background:"#fff",borderRadius:20,padding:24,marginBottom:20}}><div style={{fontSize:13,fontWeight:700,color:B,marginBottom:14}}>LANGUES</div><div style={{display:"flex",gap:10,flexWrap:"wrap"}}>{(guide.languages as string[]).map(l=><span key={l} style={{background:"#eef2ff",color:B,padding:"6px 14px",borderRadius:20,fontSize:13,fontWeight:600}}>{l}</span>)}</div></div>}
                                                                                                                                                                                                                                                                                      {guide.specialties&&(guide.specialties as string[]).length>0&&<div style={{background:"#fff",borderRadius:20,padding:24,marginBottom:20}}><div style={{fontSize:13,fontWeight:700,color:B,marginBottom:14}}>SPECIALITES</div><div style={{display:"flex",gap:10,flexWrap:"wrap"}}>{(guide.specialties as string[]).map(s=><span key={s} style={{background:"#fff7ed",color:T,padding:"6px 14px",borderRadius:20,fontSize:13,fontWeight:600}}>{s.replace(/_/g," ")}</span>)}</div></div>}
                                                                                                                                                                                                                                                                                              <div style={{background:B,borderRadius:20,padding:28,color:"#fff"}}>
                                                                                                                                                                                                                                                                                                        <div style={{fontSize:13,fontWeight:700,letterSpacing:1,marginBottom:20,opacity:0.8}}>TARIFS ET RESERVATION</div>
                                                                                                                                                                                                                                                                                                                  <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,marginBottom:24}}>
                                                                                                                                                                                                                                                                                                                              <div style={{background:"rgba(255,255,255,0.12)",borderRadius:16,padding:20,textAlign:"center"}}><div style={{fontSize:28,fontWeight:900,color:Y}}>{guide.halfDayPrice} MAD</div><div style={{fontSize:13,opacity:0.8}}>4h</div></div>
                                                                                                                                                                                                                                                                                                                                          <div style={{background:"rgba(255,255,255,0.12)",borderRadius:16,padding:20,textAlign:"center"}}><div style={{fontSize:28,fontWeight:900,color:Y}}>{guide.fullDayPrice} MAD</div><div style={{fontSize:13,opacity:0.8}}>8h</div></div>
                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                              <BookingModal guideName={guide.displayName} halfDayPrice={Number(guide.halfDayPrice)} fullDayPrice={Number(guide.fullDayPrice)} guideId={guide.id}/>
                                                                                                                                                                                                                                                                                                                                                                        <div style={{textAlign:"center",fontSize:12,opacity:0.6,marginTop:12}}>Annulation gratuite jusqu'a 24h avant</div>
                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                            }